### ISSUE TITLE
YouTube Key

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#110]
@tedw David tried to follow your instructions on getting a Key for YouTube, but ran into an issue -- please advise:

For YouTube, I followed the steps you outlined, but didn’t see a public key generated. It’s possible that I need to generate “credentials…” Can you advise on the settings in the screenshot attached?

![image002](https://user-images.githubusercontent.com/13699106/40785628-08d4c9bc-64b7-11e8-8936-6f5683eaa37b.jpg)

**Comment by tedw** [comment]
Looks like the interface changed slightly since I last originally wrote those instructions.

He should go here:
https://console.cloud.google.com/apis/library/youtube.googleapis.com/?q=youtube

Then click the "Enable" button.  On the next screen, he should click the "Credentials" link in the left sidebar. He will then see a "Create Credentials" menu, which he should click and select “API Key”

![screen shot 2018-05-31 at 11 25 15 pm](https://user-images.githubusercontent.com/864716/40819637-1c96f1dc-652a-11e8-9917-b2f3c773861b.png)

A modal window will open with the public key we need.

He should then restrict the key to only `https://*.aldf.org/*`, `localhost`, and `0.0.0.0` so other sites can’t use it.

**Comment by lizzycederberg** [comment]
Thanks @tedw

**Comment by tedw** [comment]
There is now a field for the YouTube API key in the admin
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/admin.php?page=aldf-info

**Comment by lizzycederberg** [comment]
@tedw I added their YouTube API Key to the live site!
