### ISSUE TITLE
Possible to select media in the 2-up text promo

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#137]
@tedw Can you give me an estimate for added the `add media` function to the mini WYSIWYG editor on the 2-up text promo component 

Elizabeth has started adding images via the `text` tab and wanted to know if this could be added: https://live-aldf-wp.pantheonsite.io/article/animal-law-opportunities/

**Comment by tedw** [comment]
Yeah that's not good, she should not do that to avoid broken images and migration issues in the future.

I can easily add the full WYSIWYG editor. I used the minimal one because we didn't design and write FE styles for any possible shortcode or WYSIWYG component (e.g. images, block quotes, tables, etc). It will be up to them to avoid doing anything that looks bad.

**Comment by lizzycederberg** [comment]
@tedw Ok that makes sense. I'll ask Elizabeth about that and let you know.

**Comment by lizzycederberg** [comment]
@tedw Elizabeth is ok with those limitations and will just us it for images. Please go ahead and update. Thanks!

**Comment by tedw** [comment]
Updated

**Comment by lizzycederberg** [comment]
Thanks!

**Comment by lizzycederberg** [comment]
@tedw I see that the full rich text editor is in there, but I don't see `add media` -- can you please check?

![screen shot 2018-06-19 at 3 50 25 pm](https://user-images.githubusercontent.com/13699106/41620726-96e81e90-73d8-11e8-813f-ae986ea69a4a.png)

**Comment by tedw** [comment]
Hmm, sorry, I thought it would show up so didn't actually test it. I must have missed a setting or something.

**Comment by tedw** [comment]
Added the media button and switched back to simple wysiwyg

**Comment by lizzycederberg** [comment]
Looks good!
