### ISSUE TITLE
Make nav sticky

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#144]
@cmontwill @lfhello Elizabeth said we designed the nav to be sticky. Is that true? I can't find anything about it.

@tedw Can you tell me how long it would take to make it sticky?

**Comment by cmontwill** [comment]
@lizzycederberg TBH I remember it the other way around and it wasnt spec'd that way. I believe it was one of the reasons for the back to top on the project pages. Either way, we'll have to estimate.

**Comment by tedw** [comment]
If all we’re doing is making it sticky (i.e. no layout changes once stuck, no hiding on scroll) and don’t care about IE 11 support, this will only take 10 min (plus deploy time).

**Comment by tedw** [comment]
Ready for testing

**Comment by lfhello** [comment]
Looks good to me!

**Comment by lizzycederberg** [comment]
Is this on live? I'm not seeing it

**Comment by tedw** [comment]
@lizzycederberg It only becomes sticky once if the viewport is >= 1200x900. This was done to avoid taking up too much space on small screens.

**Comment by lizzycederberg** [comment]
@tedw That makes sense -- David is reporting that he doesn't see it on his screen which is 2880x1800. Is that different than viewport?

**Comment by tedw** [comment]
To clarify for David, the header will only become sticky when the area inside the browser (i.e. viewport) is at least 1200 x 900. If his screen is 1440 x 900 (the number he gave is not the CSS size, since he has a high-res screen), then the area inside the browser window will be less than 900px tall due to the default browser UI (e.g. address bar, bookmarks, other toolbars). He can check his actual viewport size on this site https://www.mydevice.io

If he wants, we can adjust the cutoff to 800px tall so it will be sticky on 1440 x 900 size screens. The reason we have a cutoff in the first place is to avoid taking up too much screen space on smaller screens.

**Comment by lizzycederberg** [comment]
No need to change anything here!
