### ISSUE TITLE
Glossary terms not working

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#202]
@tedw 

On this page:
https://live-aldf-wp.pantheonsite.io/how_we_work/criminal-justice/
The amicus brief tag is not pulling in the text. It doesn't seem to be a content issue as "voir dire" is correct.

Also on this page: 
https://live-aldf-wp.pantheonsite.io/how_we_work/regulation/
The 'administrative procedures act' is not working. Also, the 'administrative law' term should say "The body of law relating to government agencies.", but it says "A judge who presides over administrative hearings." Lastly, 'standing' appears to be working. 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
There are a couple of issues here:

### Quotation Marks
ALDF used straight quotes (`""`) instead of real quotes (`“”`) in some definitions, which is breaking the HTML. I will try to auto-convert the quotes prior to generating the HTML but they should also be using real quotes as a best practice ([Mac keyboard shortcuts](http://quotesandaccents.com)).

### Case Sensitive
Glossary terms are **case sensitive** so each variation currently requires its own entry (e.g. Lorem Ipsum, lorem ipsum, Lorem ipsum). Additionally, **plural forms** also require separate entries.

I originally went with this solution because it meant ALDF didn’t have to look up glossary terms by ID number. I thought this would be easier for them. However in practice, it seems the ID number solution is also going to be necessary when the word in an article doesn’t exactly match the glossary entry.

Here’s my proposed solution for that:

```
[term word="voir dire" id="6355"]
```

### Custom Tooltips

Another feature I’ve been thinking about adding is the ability to create tooltips without a corresponding glossary entry. This could be done with a shortcode along these lines:

```
WordPress is a [tooltip text="content management system"]CMS[/tooltip] written in PHP.
```

This would not take long to implement, maybe 30 min. LMK if you would like me to go ahead with that.

**Comment by tedw** [comment]
In additional to the issues above, there was also a CSS issue that was cutting off the tooltip when inside of a list item.

**Comment by tedw** [comment]
I have added an optional `id` attribute to specify the glossary term if the word does not exactly match the glossary post title.

```
[term word="voir dire" id="6355"]
```

I also fixed the CSS that was causing tooltips to get cutoff when in list elements.
